
version: 2

jobs:
  build:
    docker:
      # - image: rocker/tidyverse:devel
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - run:
          command: |
            R -e \
              'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools"); devtools::install_deps(dependencies = TRUE)'
      - run:
          command: |
            R -e 'devtools::check()'
      - run:
          command: |
            mkdir test_results && \
            R -e 'devtools::test(".", reporter = testthat::JunitReporter$new(file = "test_results/testthat_result.xml"))'
      - store_artifacts:
          path: man/
          destination: man
      ## store artifacts -----------------
      - store_test_results:
          path: test_results/
          when: always
      - store_artifacts:
          path: rcicdemo.Rcheck/
          when: always
